### PR TITLE
feat: allow setting permission at bucket level

### PR DESCRIPTION
**Pull request by Eraac**
***Description:***
Allow to set `roles/storage.objectViewer` on the bucket used for the registry instead of all buckets (project level)

### CODE REVIEW

**Review by mikelaramie — APPROVED** [review]
lgtm!

**Review by afiune — APPROVED** [review]
tenor-267650693

**Comment by afiune** [comment]
@Eraac Thank you so much for your contribution!! We are almost ready to merge this PR and release this
new functionality 🙌🏽  - The only missing thing is for you to rebase and sign your commits, [this is required for any contribution to this project](https://github.com/lacework/terraform-gcp-gcr/blob/main/DEVELOPER_GUIDELINES.md#signing-commits).

Please see Github's documentation on configuring signed commits, [tell git about your signing key](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key) and [signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)[](https://github.com/)

**Comment by Eraac** [comment]
@afiune Its should be good now

**Comment by dmurray-lacework** [comment]
make it so!

**Pull request merged**
